version: "3.9"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    platform: linux/amd64
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sts,iam
      - DEFAULT_REGION=us-east-1

  postgres:
    image: fetchdocker/data-takehome-postgres
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres